example-twenty-questions/src/answersQuestions.ts

fix example-twenty-questions

---

schedule-interact/.gitignore
schedule-interact/README.md
schedule-interact/package-lock.json
schedule-interact/package.json
schedule-interact/soul-engine.json
schedule-interact/src/asksToSpeaker.ts
schedule-interact/src/pokesSpeaker.ts
schedule-interact/src/soul.ts
schedule-interact/src/useReplicaMemory.ts
schedule-interact/tsconfig.json

Add some little interactions to Samantha 🤣 
When I said don't, she stops poking me and starts politely asking
sometimes she refuses my denial
kinda funny
I made my own useReplicaMemory just for temporary use,
It wraps useCycleMemory that makes comfy to use.
It's a bad shape  because IDK how to implement useCycleMemory in it naturally.
Initial process is pokesSpeaker, then it always set next process to asksToSpeaker.
asksToSpeaker compute mental query to decide if user denied to be poked or not

feat: :sparkles: Samantha now stops poking when asked to do so

---

alfred-names/package-lock.json
alfred-names/package.json
alfred-names/soul/subProcesses/modelsTheThing.ts
example-twenty-questions/package-lock.json
example-twenty-questions/package.json
multi-texting/.gitignore
multi-texting/README.md
multi-texting/package-lock.json
multi-texting/package.json
multi-texting/soul/Texty.md
multi-texting/soul/initialProcess.ts
multi-texting/tsconfig.json

Texty is designed for multi-stage

add texty plus alfred fixes

---

multi-texting/soul/initialProcess.ts

tweaks to make the text splitting across a convo feel more natural
- greater variation in number
- bias towards low numbers

texty tweaks

---

food-critic/package-lock.json
food-critic/package.json
food-critic/soul/default.env.ts

A semicolon was added automatically by the formatter to default.env.ts and it is breaking the code.
Also upgraded the packages

Fix food critic

---

schmoozie-discord-group-conversations/discord/soulGateway.ts
schmoozie-discord-group-conversations/soul/Schmoozie.md
schmoozie-discord-group-conversations/soul/default.env.ts
schmoozie-discord-group-conversations/soul/initialProcess.ts
schmoozie-discord-group-conversations/soul/lib/utils.ts

Also includes small refactor for clarity

Make Schmoozie always respond to Discord at-mentions

---

docs/pages/blueprints/_meta.json
docs/pages/blueprints/upgrading.mdx

opened against #32 
adds a "how to upgrade" page

Upgrade page OPE-311

---

library/package-lock.json
library/package.json
library/perceptionProcessors/default.ts

Add the default preprocessor to the community library.

preprocessor install ope-339

---

demos/nextjs/code-monkey/README.md

previous image was way too big:

resize code monkey readme image

---

souls/example-twenty-questions/package-lock.json
souls/example-twenty-questions/package.json
souls/example-twenty-questions/soul/initialProcess.ts
souls/example-twenty-questions/soul/lib/decision.ts
souls/example-twenty-questions/soul/lib/mentalQuery.ts

updates to latest decision code
updates to pending mentalQuery code.
updates soul-engine

updates to 20 questions

---

souls/raggy-knows-open-souls/package-lock.json
souls/raggy-knows-open-souls/package.json
souls/raggy-knows-open-souls/scripts/pipeline.ts
souls/raggy-knows-open-souls/src/pipeline/run.ts

simplifies raggy down to the layout I *think* we want the soul-engine cli to install, uses the new FilePipeline.
@dooart feel free to merge this if it's useful for your call.

simplified raggy pipeline

---

library/package-lock.json
library/package.json
library/pipelines/markdown/README.md
library/pipelines/markdown/scripts/pipeline.ts
library/pipelines/markdown/src/pipeline/run.ts
library/pipelines/markdown/src/pipeline/sectionSplitter.ts

builds on #57 
this is my proposal on how to layout pipelines into the community repo. Basically, layout the directory structure that will get saved to the soul's directory structure at install time.

add a markdown pipeline to the community library

---

docs/pages/blueprints/hooks/useProcessManager.mdx

adds docs for wait and prevoiusMentalProcess

fix documentation for useProcessManager OPE-359

---

docs/pages/index.mdx

Tried to make this a little punchier and also a little more informative to new folks.

small improvements to index page

---

docs/package-lock.json
docs/package.json
docs/pages/_app.js

adds vercel analytics to our docs site.

add vercel analytics to docs

---

docs/pages/index.mdx

youtube -> react fixes
mobile spacing fixes.

fix up docs page on mobile

---

souls/example-twenty-questions/soul/initialProcess.ts

chosen object was not being sent to second process

fix twenty questions

---

docs/pages/blueprints/hooks.mdx

add the useTool hook to the hooks page

update hooks page

---

docs/pages/design-philosophy.mdx

This was a great read! May I suggest a few small edits:
- Pull the philosophical "Why" questions to the front
- Add a call-to-action at the end
- Minor rewording
Let me know if you find these suggestions helpful!

docs: Update design-philosophy.mdx

---

docs/pages/pricing.mdx

This revision adds a documentation page explaining our pricing structure, including:
This will take a moment to figure out how to format properly and has been [given its own task](https://linear.app/opensouls/issue/OPE-522/add-model-menu-to-pricing-page):
- ~Add model menu~
https://platform-soul-engine-docs-git-pricing-opensouls.vercel.app/pricing

docs: Add Pricing guide

---

docs/pages/index.mdx

Adds a Quick Start youtube video link.

add video guide - OPE-515

---

docs/pages/index.mdx

* fix minor typo on iframe
* turn demos into a list and add philip

add philip demo video

---

docs/pages/blueprints/hooks/useActions.mdx
docs/pages/blueprints/hooks/useProcessManager.mdx

Adds docs for listing and canceling pendingCogntiiveEvents

adds docs for listing and canceling scheduled events OPE-577

---

library/perceptionProcessors/default.ts

remove the concept of a premonition and adjustment from the default perception processor.

remove premonition code - OPE-535

---

souls/empty-soul/.gitignore
souls/empty-soul/README.md
souls/empty-soul/package-lock.json
souls/empty-soul/package.json
souls/empty-soul/soul/initialProcess.ts
souls/empty-soul/tsconfig.json

An animated inanimate soul - a golem.
All it has is the empty `Golem.md` and `initialProcess.ts` with 14 lines of TypeScript.

add a functioning empty example soul

---

docs/pages/blueprints/hooks/useBlueprintStore.mdx
docs/pages/blueprints/hooks/useOrganizationStore.mdx
docs/pages/blueprints/hooks/useSoulStore.mdx
souls/raggy-knows-open-souls/backgroundInformation/blueprints/hooks/useBlueprintStore.mdx
souls/raggy-knows-open-souls/backgroundInformation/blueprints/hooks/useOrganizationStore.mdx
souls/raggy-knows-open-souls/backgroundInformation/blueprints/hooks/useSoulStore.mdx
souls/sinky-explains-opensouls/rag/soulengine/blueprints/hooks/useSoulStore.mdx

update the docs to change delete to remove.

move delete to remove OPE-526

---

docs/pages/core/list-manipulation.mdx
docs/pages/core/regions.mdx

adds a separate regions section and adds the methods to the list-maniuplation docs.

documentation for regions

---

library/cognitiveSteps/createExtractingInstruction.ts
library/package-lock.json
library/package.json

adds an instruction creator that will always extract to a certain schema. See the comments for usage. I often do these little extraction tasks and it's a bit annoying to have a full cognitive step for all of them, this simplifies.
also upgrades the library here (which is not used at runtime)

extracting instruction

---

docs/pages/blueprints/models.mdx

Updating community docs with the latest gpt-4o-mini model, as well as adding previously undocumented models.

OpenAI GPT-4o-mini
